name: Build and Push Docker image
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: n4vip/n4sshx2:latest   # ← သင့် Docker Hub repo အတိုင်း
          no-cache: true               # ← healthz version ကို 強制 rebuild
          platforms: linux/amd64
